### ISSUE TITLE
Some parts of `Euclidean` belong in weaker structures.

### ISSUE THREAD

**Issue by dfoxfranke** [ekmett/algebra#10]
You don't have to have a Euclidean domain to have a GCD. In the polynomial library I'm working on, I currently have this instance:

```haskell
instance (Euclidean a) => Euclidean (Poly a)
```

But it's a dirty lie. R[x] is a Euclidean domain if R is a field, but if R is only a Euclidean domain then R[x] is only a UFD. To make this instance work, I have to modify the default definition of `euclid` to factor out the content and primitive part of the polynomial and then run the standard Euclidean algorithm in polynomials over the fraction field.

Much of what's currently in `Euclidean` belongs in weaker structures, like a GCD domain or a UFD. I'll follow up with a concrete proposal once I have one.

**Comment by konn** [comment]
Fixed by #12 (Thanks @dfoxfranke )!
