### ISSUE TITLE
Not compatible with semigroupoids-6, transformers-0.6

### ISSUE THREAD

**Issue by ysangkok** [ekmett/algebra#29]
semigroupoids-6 is the first series compatible with GHC 9.6, and transformers-0.6 is the release shipped with GHC 9.6. See also

* https://github.com/commercialhaskell/stackage/issues/6909
* https://github.com/commercialhaskell/stackage/issues/6857

EDIT: also need to bump mtl

**Comment by cartazio** [comment]
Is this just a version bound issue or what is failing?

**Comment by ysangkok** [comment]
It's just a version bound issue, at least 

    cabal build -w ghc-9.6.1 --allow-newer=algebra:semigroupoids,algebra:transformers,algebra:mtl

compiles with no issue. (There are no tests)

**Comment by ysangkok** [comment]
@cartazio If you are maintaining this now, a revision would be appreciated.

**Comment by cartazio** [comment]
I'm not an uploader on hackage, but i'mhappy to do this process if ed gives me the perms

see "uploaders" on https://hackage.haskell.org/package/algebra

**Comment by ysangkok** [comment]
Apologies, I should have checked there. @jeltsch would you be willing to do this bump?

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision: https://hackage.haskell.org/package/algebra-4.3.1/revisions/

**Comment by cartazio** [comment]
Thx
